### ISSUE TITLE
Inventory way that we are using dates in various applications

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/sul_styles#8]

**Comment by jkeck** [comment]
## SUL Requests

```
  date:
    formats:
      quick: '%a %b %-d'
      short: '%b %-d %Y'
      long: '%A, %b %-d %Y'
  time:
    am: a
    pm: p
    formats:
      short: '%Y-%m-%d %l.%M%P'
```
